import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
//import { Amplify } from 'aws-amplify';
//import amplifyconfig from '../amplifyconfiguration.json';

//Amplify.configure(amplifyconfig);

/* import { Amplify } from 'aws-amplify';
import awsconfig from '../aws-exports';
Amplify.configure(awsconfig);
const existingConfig = Amplify.getConfig();

Amplify.configure({
  ...existingConfig,
  API:{
    ...existingConfig.API,
    REST:{
      ...existingConfig.API?.REST,
      'intouchapi':{
        endpoint:'https://ckojh75t4f.execute-api.us-east-1.amazonaws.com/dev',
        region:'us-east-1'
      }
    }
  }
}) */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{



  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
